### PR TITLE
Move `ComponentData` message to `components.proto`

### PR DESCRIPTION
**Pull request by tiyash-basu-frequenz**

### CODE REVIEW

**Review by thomas-nicolai-frequenz — DISMISSED** [review]

**Comment by tiyash-basu-frequenz** [comment]
Rebased on top of v0.x.x.

**Review by stefan-brus-frequenz — COMMENTED** [review]
Does this need release notes?

**Comment by tiyash-basu-frequenz** [comment]
> Does this need release notes?

Release notes were already added for `ComponentData`. This PR just moves it to a different package/path. Not sure how to add a release note about the package/path change without making it confusing ..

**Review by stefan-brus-frequenz — DISMISSED** [review]

**Comment by tiyash-basu-frequenz** [comment]
Rebased. Added a typo fix as a part of resolving the conflict.

**Review by stefan-brus-frequenz — APPROVED** [review]

**Pull request merged**
